version: '3.8'

services:
  restaurante:
    image: postgres:latest
    container_name: restaurante_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=restaurantedb
    ports:
      - "5433:5432"

  reservas-app:
    image: julioborges05/reservas-app
    container_name: reservas_app
    environment:
      - DB_URL=jdbc:postgresql://restaurante:5432/restaurantedb
      - DB_USER=user
      - DB_PASSWORD=password
    depends_on:
      - restaurante
    ports:
      - "8080:8080"